#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LCPS.v2015.v001.NwUsers.HumanResources.Staff
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="NWUsers.Lcps.v2015.v004")]
	public partial class HRStaffContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public HRStaffContext() : 
				base(global::LCPS.v2015.v001.NwUsers.Properties.Settings.Default._connectionString, mappingSource)
		{
			OnCreated();
		}
		
		public HRStaffContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public HRStaffContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public HRStaffContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public HRStaffContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<HRStaffRecord> HRStaffRecords
		{
			get
			{
				return this.GetTable<HRStaffRecord>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="HumanResources.HRStaffRecord")]
	public partial class HRStaffRecord
	{
		
		private System.Guid _PositionKey;
		
		private int _StatusVal;
		
		private string _FiscalYear;
		
		private System.Guid _BuildingKey;
		
		private string _BuildingId;
		
		private string _BuildingName;
		
		private string _Description;
		
		private System.Guid _EmployeeTypeKey;
		
		private string _EmployeeTypeId;
		
		private string _EmployeeTypeName;
		
		private int _Category;
		
		private System.Guid _StaffKey;
		
		private string _StaffId;
		
		private string _FirstName;
		
		private string _MiddleInitial;
		
		private string _LastName;
		
		private int _GenderVal;
		
		private System.DateTime _Birthdate;
		
		private System.Guid _JobTitleKey;
		
		private string _JobTitleId;
		
		private string _JobTitleName;
		
		public HRStaffRecord()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PositionKey", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid PositionKey
		{
			get
			{
				return this._PositionKey;
			}
			set
			{
				if ((this._PositionKey != value))
				{
					this._PositionKey = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StatusVal", DbType="Int NOT NULL")]
		public int StatusVal
		{
			get
			{
				return this._StatusVal;
			}
			set
			{
				if ((this._StatusVal != value))
				{
					this._StatusVal = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FiscalYear", DbType="NVarChar(MAX)")]
		public string FiscalYear
		{
			get
			{
				return this._FiscalYear;
			}
			set
			{
				if ((this._FiscalYear != value))
				{
					this._FiscalYear = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BuildingKey", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid BuildingKey
		{
			get
			{
				return this._BuildingKey;
			}
			set
			{
				if ((this._BuildingKey != value))
				{
					this._BuildingKey = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BuildingId", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string BuildingId
		{
			get
			{
				return this._BuildingId;
			}
			set
			{
				if ((this._BuildingId != value))
				{
					this._BuildingId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BuildingName", DbType="NVarChar(128) NOT NULL", CanBeNull=false)]
		public string BuildingName
		{
			get
			{
				return this._BuildingName;
			}
			set
			{
				if ((this._BuildingName != value))
				{
					this._BuildingName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="NVarChar(256)")]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this._Description = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmployeeTypeKey", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid EmployeeTypeKey
		{
			get
			{
				return this._EmployeeTypeKey;
			}
			set
			{
				if ((this._EmployeeTypeKey != value))
				{
					this._EmployeeTypeKey = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmployeeTypeId", DbType="NVarChar(15) NOT NULL", CanBeNull=false)]
		public string EmployeeTypeId
		{
			get
			{
				return this._EmployeeTypeId;
			}
			set
			{
				if ((this._EmployeeTypeId != value))
				{
					this._EmployeeTypeId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmployeeTypeName", DbType="NVarChar(128) NOT NULL", CanBeNull=false)]
		public string EmployeeTypeName
		{
			get
			{
				return this._EmployeeTypeName;
			}
			set
			{
				if ((this._EmployeeTypeName != value))
				{
					this._EmployeeTypeName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Category", DbType="Int NOT NULL")]
		public int Category
		{
			get
			{
				return this._Category;
			}
			set
			{
				if ((this._Category != value))
				{
					this._Category = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StaffKey", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid StaffKey
		{
			get
			{
				return this._StaffKey;
			}
			set
			{
				if ((this._StaffKey != value))
				{
					this._StaffKey = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StaffId", DbType="NVarChar(25) NOT NULL", CanBeNull=false)]
		public string StaffId
		{
			get
			{
				return this._StaffId;
			}
			set
			{
				if ((this._StaffId != value))
				{
					this._StaffId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FirstName", DbType="NVarChar(75) NOT NULL", CanBeNull=false)]
		public string FirstName
		{
			get
			{
				return this._FirstName;
			}
			set
			{
				if ((this._FirstName != value))
				{
					this._FirstName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MiddleInitial", DbType="NVarChar(3)")]
		public string MiddleInitial
		{
			get
			{
				return this._MiddleInitial;
			}
			set
			{
				if ((this._MiddleInitial != value))
				{
					this._MiddleInitial = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastName", DbType="NVarChar(75) NOT NULL", CanBeNull=false)]
		public string LastName
		{
			get
			{
				return this._LastName;
			}
			set
			{
				if ((this._LastName != value))
				{
					this._LastName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GenderVal", DbType="Int NOT NULL")]
		public int GenderVal
		{
			get
			{
				return this._GenderVal;
			}
			set
			{
				if ((this._GenderVal != value))
				{
					this._GenderVal = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Birthdate", DbType="DateTime NOT NULL")]
		public System.DateTime Birthdate
		{
			get
			{
				return this._Birthdate;
			}
			set
			{
				if ((this._Birthdate != value))
				{
					this._Birthdate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_JobTitleKey", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid JobTitleKey
		{
			get
			{
				return this._JobTitleKey;
			}
			set
			{
				if ((this._JobTitleKey != value))
				{
					this._JobTitleKey = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_JobTitleId", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string JobTitleId
		{
			get
			{
				return this._JobTitleId;
			}
			set
			{
				if ((this._JobTitleId != value))
				{
					this._JobTitleId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_JobTitleName", DbType="NVarChar(128) NOT NULL", CanBeNull=false)]
		public string JobTitleName
		{
			get
			{
				return this._JobTitleName;
			}
			set
			{
				if ((this._JobTitleName != value))
				{
					this._JobTitleName = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
