// <auto-generated />
namespace LCPS.v2015.v001.WebUI.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class FilterNew_001 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FilterNew_001));
        
        string IMigrationMetadata.Id
        {
            get { return "201507122353373_FilterNew_001"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
