// <auto-generated />
namespace LCPS.v2015.v001.WebUI.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class Email002 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Email002));
        
        string IMigrationMetadata.Id
        {
            get { return "201507231223047_Email002"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
