// <auto-generated />
namespace LCPS.v2015.v001.WebUI.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class HREmplioyeeTypeSchema01 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(HREmplioyeeTypeSchema01));
        
        string IMigrationMetadata.Id
        {
            get { return "201507021835550_HREmplioyeeTypeSchema01"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
