<?xml version="1.0" encoding="utf-8"?><Database Name="NWUsers.Lcps.v2015.v004" EntityNamespace="LCPS.v2015.v001.NwUsers.LcpsEmail" ContextNamespace="LCPS.v2015.v001.NwUsers.LcpsEmail" Class="LcpsEmailContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=.\sqlexpress;Initial Catalog=NWUsers.Lcps.v2015.v004;Integrated Security=False;User ID=Sa" SettingsObjectName="LCPS.v2015.v001.NwUsers.Properties.Settings" SettingsPropertyName="_connectionString" Provider="System.Data.SqlClient" />
  <Table Name="LcpsEmail.LcpsEmailKey" Member="LcpsEmailKeys">
    <Type Name="LcpsEmailKey">
      <Column Name="EmailAddress" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="StudentKey" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="StaffKey" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="StuFirstName" Type="System.String" DbType="NVarChar(75)" CanBeNull="true" />
      <Column Name="StuLastName" Type="System.String" DbType="NVarChar(75)" CanBeNull="true" />
      <Column Name="StfFirstName" Type="System.String" DbType="NVarChar(75)" CanBeNull="true" />
      <Column Name="StfLastName" Type="System.String" DbType="NVarChar(75)" CanBeNull="true" />
    </Type>
  </Table>
</Database>