#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LCPS.v2015.v001.NwUsers.LcpsEmail
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="NWUsers.Lcps.v2015.v004")]
	public partial class LcpsEmailContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public LcpsEmailContext() : 
				base(global::LCPS.v2015.v001.NwUsers.Properties.Settings.Default._connectionString, mappingSource)
		{
			OnCreated();
		}
		
		public LcpsEmailContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LcpsEmailContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LcpsEmailContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LcpsEmailContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<LcpsEmailKey> LcpsEmailKeys
		{
			get
			{
				return this.GetTable<LcpsEmailKey>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="LcpsEmail.LcpsEmailKey")]
	public partial class LcpsEmailKey
	{
		
		private string _EmailAddress;
		
		private System.Nullable<System.Guid> _StudentKey;
		
		private System.Nullable<System.Guid> _StaffKey;
		
		private string _StuFirstName;
		
		private string _StuLastName;
		
		private string _StfFirstName;
		
		private string _StfLastName;
		
		public LcpsEmailKey()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmailAddress", DbType="NVarChar(MAX)")]
		public string EmailAddress
		{
			get
			{
				return this._EmailAddress;
			}
			set
			{
				if ((this._EmailAddress != value))
				{
					this._EmailAddress = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StudentKey", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> StudentKey
		{
			get
			{
				return this._StudentKey;
			}
			set
			{
				if ((this._StudentKey != value))
				{
					this._StudentKey = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StaffKey", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> StaffKey
		{
			get
			{
				return this._StaffKey;
			}
			set
			{
				if ((this._StaffKey != value))
				{
					this._StaffKey = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StuFirstName", DbType="NVarChar(75)")]
		public string StuFirstName
		{
			get
			{
				return this._StuFirstName;
			}
			set
			{
				if ((this._StuFirstName != value))
				{
					this._StuFirstName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StuLastName", DbType="NVarChar(75)")]
		public string StuLastName
		{
			get
			{
				return this._StuLastName;
			}
			set
			{
				if ((this._StuLastName != value))
				{
					this._StuLastName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StfFirstName", DbType="NVarChar(75)")]
		public string StfFirstName
		{
			get
			{
				return this._StfFirstName;
			}
			set
			{
				if ((this._StfFirstName != value))
				{
					this._StfFirstName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StfLastName", DbType="NVarChar(75)")]
		public string StfLastName
		{
			get
			{
				return this._StfLastName;
			}
			set
			{
				if ((this._StfLastName != value))
				{
					this._StfLastName = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
