<?xml version="1.0" encoding="utf-8"?><Database Name="LCPS.NwUsers.V001" EntityNamespace="LCPS.v2015.v001.NwUsers.LcpsLdap.LdapAccounts" ContextNamespace="LCPS.v2015.v001.NwUsers.LcpsLdap.LdapAccounts" Class="LdapAccountContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=.\sqlexpress;Initial Catalog=NWUsers.Lcps.v2015.v004;Integrated Security=False;User ID=Sa" SettingsObjectName="LCPS.v2015.v001.NwUsers.Properties.Settings" SettingsPropertyName="_connectionString" Provider="System.Data.SqlClient" />
  <Table Name="LcpsLdap.[LdapAccount-Staff]" Member="StaffLdapAccounts">
    <Type Name="StaffLdapAccount">
      <Column Name="StaffId" Type="System.String" DbType="NVarChar(25) NOT NULL" CanBeNull="false" />
      <Column Name="LastName" Type="System.String" DbType="NVarChar(75) NOT NULL" CanBeNull="false" />
      <Column Name="FirstName" Type="System.String" DbType="NVarChar(75) NOT NULL" CanBeNull="false" />
      <Column Name="MiddleInitial" Type="System.String" DbType="NVarChar(3)" CanBeNull="true" />
      <Column Name="UserName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Active" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="LcpsLdap.[Ldap-Staff-Import]" Member="LdapStaffImportRecords">
    <Type Name="LdapStaffImportRecord">
      <Column Name="StaffKey" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="StaffId" Type="System.String" DbType="NVarChar(25) NOT NULL" CanBeNull="false" />
      <Column Name="LastName" Type="System.String" DbType="NVarChar(75) NOT NULL" CanBeNull="false" />
      <Column Name="FirstName" Type="System.String" DbType="NVarChar(75) NOT NULL" CanBeNull="false" />
      <Column Name="MiddleInitial" Type="System.String" DbType="NVarChar(3)" CanBeNull="true" />
      <Column Name="BuildingKey" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="BuildingName" Type="System.String" DbType="NVarChar(128) NOT NULL" CanBeNull="false" />
      <Column Name="EmployeeTypeKey" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="EmployeeTypeName" Type="System.String" DbType="NVarChar(128) NOT NULL" CanBeNull="false" />
      <Column Name="JobTitleKey" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="JobTitleName" Type="System.String" DbType="NVarChar(128) NOT NULL" CanBeNull="false" />
      <Column Name="StatusVal" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="AccountId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="UserName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="InitialPassword" Type="System.String" DbType="NVarChar(256) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>