#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LCPS.v2015.v001.NwUsers.LcpsLdap.LdapAccounts
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="LCPS.NwUsers.V001")]
	public partial class LdapAccountContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public LdapAccountContext() : 
				base(global::LCPS.v2015.v001.NwUsers.Properties.Settings.Default._connectionString, mappingSource)
		{
			OnCreated();
		}
		
		public LdapAccountContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LdapAccountContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LdapAccountContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LdapAccountContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<StaffLdapAccount> StaffLdapAccounts
		{
			get
			{
				return this.GetTable<StaffLdapAccount>();
			}
		}
		
		public System.Data.Linq.Table<LdapStaffImportRecord> LdapStaffImportRecords
		{
			get
			{
				return this.GetTable<LdapStaffImportRecord>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="LcpsLdap.[LdapAccount-Staff]")]
	public partial class StaffLdapAccount
	{
		
		private string _StaffId;
		
		private string _LastName;
		
		private string _FirstName;
		
		private string _MiddleInitial;
		
		private string _UserName;
		
		private bool _Active;
		
		public StaffLdapAccount()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StaffId", DbType="NVarChar(25) NOT NULL", CanBeNull=false)]
		public string StaffId
		{
			get
			{
				return this._StaffId;
			}
			set
			{
				if ((this._StaffId != value))
				{
					this._StaffId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastName", DbType="NVarChar(75) NOT NULL", CanBeNull=false)]
		public string LastName
		{
			get
			{
				return this._LastName;
			}
			set
			{
				if ((this._LastName != value))
				{
					this._LastName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FirstName", DbType="NVarChar(75) NOT NULL", CanBeNull=false)]
		public string FirstName
		{
			get
			{
				return this._FirstName;
			}
			set
			{
				if ((this._FirstName != value))
				{
					this._FirstName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MiddleInitial", DbType="NVarChar(3)")]
		public string MiddleInitial
		{
			get
			{
				return this._MiddleInitial;
			}
			set
			{
				if ((this._MiddleInitial != value))
				{
					this._MiddleInitial = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserName", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string UserName
		{
			get
			{
				return this._UserName;
			}
			set
			{
				if ((this._UserName != value))
				{
					this._UserName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Active", DbType="Bit NOT NULL")]
		public bool Active
		{
			get
			{
				return this._Active;
			}
			set
			{
				if ((this._Active != value))
				{
					this._Active = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="LcpsLdap.[Ldap-Staff-Import]")]
	public partial class LdapStaffImportRecord
	{
		
		private System.Guid _StaffKey;
		
		private string _StaffId;
		
		private string _LastName;
		
		private string _FirstName;
		
		private string _MiddleInitial;
		
		private System.Guid _BuildingKey;
		
		private string _BuildingName;
		
		private System.Guid _EmployeeTypeKey;
		
		private string _EmployeeTypeName;
		
		private System.Guid _JobTitleKey;
		
		private string _JobTitleName;
		
		private int _StatusVal;
		
		private System.Guid _AccountId;
		
		private string _UserName;
		
		private string _InitialPassword;
		
		public LdapStaffImportRecord()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StaffKey", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid StaffKey
		{
			get
			{
				return this._StaffKey;
			}
			set
			{
				if ((this._StaffKey != value))
				{
					this._StaffKey = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StaffId", DbType="NVarChar(25) NOT NULL", CanBeNull=false)]
		public string StaffId
		{
			get
			{
				return this._StaffId;
			}
			set
			{
				if ((this._StaffId != value))
				{
					this._StaffId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastName", DbType="NVarChar(75) NOT NULL", CanBeNull=false)]
		public string LastName
		{
			get
			{
				return this._LastName;
			}
			set
			{
				if ((this._LastName != value))
				{
					this._LastName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FirstName", DbType="NVarChar(75) NOT NULL", CanBeNull=false)]
		public string FirstName
		{
			get
			{
				return this._FirstName;
			}
			set
			{
				if ((this._FirstName != value))
				{
					this._FirstName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MiddleInitial", DbType="NVarChar(3)")]
		public string MiddleInitial
		{
			get
			{
				return this._MiddleInitial;
			}
			set
			{
				if ((this._MiddleInitial != value))
				{
					this._MiddleInitial = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BuildingKey", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid BuildingKey
		{
			get
			{
				return this._BuildingKey;
			}
			set
			{
				if ((this._BuildingKey != value))
				{
					this._BuildingKey = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BuildingName", DbType="NVarChar(128) NOT NULL", CanBeNull=false)]
		public string BuildingName
		{
			get
			{
				return this._BuildingName;
			}
			set
			{
				if ((this._BuildingName != value))
				{
					this._BuildingName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmployeeTypeKey", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid EmployeeTypeKey
		{
			get
			{
				return this._EmployeeTypeKey;
			}
			set
			{
				if ((this._EmployeeTypeKey != value))
				{
					this._EmployeeTypeKey = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmployeeTypeName", DbType="NVarChar(128) NOT NULL", CanBeNull=false)]
		public string EmployeeTypeName
		{
			get
			{
				return this._EmployeeTypeName;
			}
			set
			{
				if ((this._EmployeeTypeName != value))
				{
					this._EmployeeTypeName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_JobTitleKey", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid JobTitleKey
		{
			get
			{
				return this._JobTitleKey;
			}
			set
			{
				if ((this._JobTitleKey != value))
				{
					this._JobTitleKey = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_JobTitleName", DbType="NVarChar(128) NOT NULL", CanBeNull=false)]
		public string JobTitleName
		{
			get
			{
				return this._JobTitleName;
			}
			set
			{
				if ((this._JobTitleName != value))
				{
					this._JobTitleName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StatusVal", DbType="Int NOT NULL")]
		public int StatusVal
		{
			get
			{
				return this._StatusVal;
			}
			set
			{
				if ((this._StatusVal != value))
				{
					this._StatusVal = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AccountId", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid AccountId
		{
			get
			{
				return this._AccountId;
			}
			set
			{
				if ((this._AccountId != value))
				{
					this._AccountId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserName", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string UserName
		{
			get
			{
				return this._UserName;
			}
			set
			{
				if ((this._UserName != value))
				{
					this._UserName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InitialPassword", DbType="NVarChar(256) NOT NULL", CanBeNull=false)]
		public string InitialPassword
		{
			get
			{
				return this._InitialPassword;
			}
			set
			{
				if ((this._InitialPassword != value))
				{
					this._InitialPassword = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
