#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LCPS.v2015.v001.NwUsers.Students
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="NWUsers.Lcps.v2015.v004")]
	public partial class StudentsContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public StudentsContext() : 
				base(global::LCPS.v2015.v001.NwUsers.Properties.Settings.Default.ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public StudentsContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public StudentsContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public StudentsContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public StudentsContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<StudentRecord> StudentRecords
		{
			get
			{
				return this.GetTable<StudentRecord>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="Students.StudentRecord")]
	public partial class StudentRecord
	{
		
		private System.Guid _StudentKey;
		
		private string _FirstName;
		
		private string _MiddleInitial;
		
		private string _LastName;
		
		private int _GenderVal;
		
		private System.DateTime _Birthdate;
		
		private string _StudentId;
		
		private System.Guid _InstructionalLevelKey;
		
		private string _InstructionalLevelId;
		
		private string _InstructionalLevelName;
		
		private System.Guid _BuildingKey;
		
		private string _BuildingId;
		
		private string _Name;
		
		private string _Description;
		
		private int _StatusVal;
		
		private string _SchoolYear;
		
		public StudentRecord()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StudentKey", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid StudentKey
		{
			get
			{
				return this._StudentKey;
			}
			set
			{
				if ((this._StudentKey != value))
				{
					this._StudentKey = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FirstName", DbType="NVarChar(75) NOT NULL", CanBeNull=false)]
		public string FirstName
		{
			get
			{
				return this._FirstName;
			}
			set
			{
				if ((this._FirstName != value))
				{
					this._FirstName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MiddleInitial", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string MiddleInitial
		{
			get
			{
				return this._MiddleInitial;
			}
			set
			{
				if ((this._MiddleInitial != value))
				{
					this._MiddleInitial = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastName", DbType="NVarChar(75) NOT NULL", CanBeNull=false)]
		public string LastName
		{
			get
			{
				return this._LastName;
			}
			set
			{
				if ((this._LastName != value))
				{
					this._LastName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="Gender", Storage="_GenderVal", DbType="Int NOT NULL")]
		public int GenderVal
		{
			get
			{
				return this._GenderVal;
			}
			set
			{
				if ((this._GenderVal != value))
				{
					this._GenderVal = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Birthdate", DbType="DateTime NOT NULL")]
		public System.DateTime Birthdate
		{
			get
			{
				return this._Birthdate;
			}
			set
			{
				if ((this._Birthdate != value))
				{
					this._Birthdate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StudentId", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string StudentId
		{
			get
			{
				return this._StudentId;
			}
			set
			{
				if ((this._StudentId != value))
				{
					this._StudentId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InstructionalLevelKey", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid InstructionalLevelKey
		{
			get
			{
				return this._InstructionalLevelKey;
			}
			set
			{
				if ((this._InstructionalLevelKey != value))
				{
					this._InstructionalLevelKey = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InstructionalLevelId", DbType="NVarChar(25) NOT NULL", CanBeNull=false)]
		public string InstructionalLevelId
		{
			get
			{
				return this._InstructionalLevelId;
			}
			set
			{
				if ((this._InstructionalLevelId != value))
				{
					this._InstructionalLevelId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InstructionalLevelName", DbType="NVarChar(128) NOT NULL", CanBeNull=false)]
		public string InstructionalLevelName
		{
			get
			{
				return this._InstructionalLevelName;
			}
			set
			{
				if ((this._InstructionalLevelName != value))
				{
					this._InstructionalLevelName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BuildingKey", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid BuildingKey
		{
			get
			{
				return this._BuildingKey;
			}
			set
			{
				if ((this._BuildingKey != value))
				{
					this._BuildingKey = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BuildingId", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string BuildingId
		{
			get
			{
				return this._BuildingId;
			}
			set
			{
				if ((this._BuildingId != value))
				{
					this._BuildingId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="Name", Storage="_Name", DbType="NVarChar(128) NOT NULL", CanBeNull=false)]
		public string BuildingName
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this._Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="NVarChar(256)")]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this._Description = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="Status", Storage="_StatusVal", DbType="Int NOT NULL")]
		public int StatusVal
		{
			get
			{
				return this._StatusVal;
			}
			set
			{
				if ((this._StatusVal != value))
				{
					this._StatusVal = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SchoolYear", DbType="NVarChar(4) NOT NULL", CanBeNull=false)]
		public string SchoolYear
		{
			get
			{
				return this._SchoolYear;
			}
			set
			{
				if ((this._SchoolYear != value))
				{
					this._SchoolYear = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
